-- CreateTable
CREATE TABLE "covid" (
    "id" SERIAL NOT NULL,
    "code" VARCHAR(10),
    "country" VARCHAR(50) NOT NULL,
    "continent" VARCHAR(50),
    "date" DATE NOT NULL,
    "total_cases" DOUBLE PRECISION,
    "new_cases" DOUBLE PRECISION,
    "new_cases_smoothed" REAL,
    "total_deaths" DOUBLE PRECISION,
    "new_deaths" DOUBLE PRECISION,
    "new_deaths_smoothed" REAL,
    "total_cases_per_million" REAL,
    "new_cases_per_million" REAL,
    "new_cases_smoothed_per_million" REAL,
    "total_deaths_per_million" REAL,
    "new_deaths_per_million" REAL,
    "new_deaths_smoothed_per_million" REAL,
    "reproduction_rate" REAL,
    "icu_patients" DOUBLE PRECISION,
    "icu_patients_per_million" REAL,
    "hosp_patients" DOUBLE PRECISION,
    "hosp_patients_per_million" REAL,
    "weekly_icu_admissions" DOUBLE PRECISION,
    "weekly_icu_admissions_per_million" REAL,
    "weekly_hosp_admissions" DOUBLE PRECISION,
    "weekly_hosp_admissions_per_million" REAL,
    "total_tests" DOUBLE PRECISION,
    "new_tests" DOUBLE PRECISION,
    "total_tests_per_thousand" REAL,
    "new_tests_per_thousand" REAL,
    "new_tests_smoothed" REAL,
    "new_tests_smoothed_per_thousand" REAL,
    "positive_rate" REAL,
    "tests_per_case" REAL,
    "tests_units" VARCHAR(50),
    "total_vaccinations" DOUBLE PRECISION,
    "people_vaccinated" DOUBLE PRECISION,
    "people_fully_vaccinated" DOUBLE PRECISION,
    "total_boosters" DOUBLE PRECISION,
    "new_vaccinations" DOUBLE PRECISION,
    "new_vaccinations_smoothed" REAL,
    "total_vaccinations_per_hundred" REAL,
    "people_vaccinated_per_hundred" REAL,
    "people_fully_vaccinated_per_hundred" REAL,
    "total_boosters_per_hundred" REAL,
    "new_vaccinations_smoothed_per_million" REAL,
    "new_people_vaccinated_smoothed" REAL,
    "new_people_vaccinated_smoothed_per_hundred" REAL,
    "stringency_index" REAL,
    "population_density" REAL,
    "median_age" REAL,
    "aged_65_older" REAL,
    "aged_70_older" REAL,
    "gdp_per_capita" REAL,
    "extreme_poverty" REAL,
    "cardiovasc_death_rate" REAL,
    "diabetes_prevalence" REAL,
    "female_smokers" REAL,
    "male_smokers" REAL,
    "handwashing_facilities" REAL,
    "hospital_beds_per_thousand" REAL,
    "life_expectancy" REAL,
    "human_development_index" REAL,
    "population" BIGINT,
    "excess_mortality_cumulative_absolute" REAL,
    "excess_mortality_cumulative" REAL,
    "excess_mortality" REAL,
    "excess_mortality_cumulative_per_million" REAL,

    CONSTRAINT "covid_pkey" PRIMARY KEY ("id")
);
