version: '3.4'
services:
  integresql:
    image: allaboutapps/integresql:latest
    expose:
      - '5001'
    ports:
      - '5001:5001'
    depends_on:
      - timescaleDb
    environment:
      INTEGRESQL_PORT: 5001
      INTEGRESQL_DB_PREFIX: 'covid'
      INTEGRESQL_TEST_DB_PREFIX: 'instance'
      PGDATABASE: &PGDATABASE 'test_db'
      PGUSER: &PGUSER 'postgres'
      PGPASSWORD: &PGPASSWORD 'password'
      PGHOST: &PGHOST 'timescaleDb'
      PGPORT: &PGPORT '5432'
      # PGSSLMODE: &PSQL_SSLMODE 'disable'
      # INTEGRESQL_TEST_INITIAL_POOL_SIZE: 50
      # INTEGRESQL_TEST_MAX_POOL_SIZE: 500

  timescaleDb:
    image: postgres:17.2
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: *PGDATABASE
      POSTGRES_USER: *PGUSER
      POSTGRES_PASSWORD: *PGPASSWORD
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    name: dev-db
